# Generated by Django 4.2.13 on 2024-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_sensor_measurement_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
